sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t tonyhawz/rpi-traefik:build .
# test image
- docker run tonyhawz/rpi-traefik:build version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep download Dockerfile | sed 's,.*/download/,,' | sed 's,/.*$,,')
    docker tag tonyhawz/rpi-traefik:build tonyhawz/rpi-traefik:$TAG
    docker push tonyhawz/rpi-traefik:$TAG
    docker tag tonyhawz/rpi-traefik:build tonyhawz/rpi-traefik:latest
    docker push tonyhawz/rpi-traefik:latest
  fi
